cmake_minimum_required(VERSION 3.16)
project(codescoring_cpp_benchmark CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(ZLIB REQUIRED)
find_package(OpenSSL REQUIRED)
add_executable(codescoring_cpp_benchmark src/main.cpp)
target_link_libraries(codescoring_cpp_benchmark PRIVATE ZLIB::ZLIB OpenSSL::SSL OpenSSL::Crypto)
